name: SSH deploy on push
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy & Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            cd ~/www/luxecosmetics.ru
            git reset --hard
            git pull
            composer install
            php artisan migrate
            php artisan view:clear
            npm install
            npm run build
