name: SSH deploy on push
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy & Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            cd ~/www/luxecosmetics.ru
            git reset --hard
            git pull
            /opt/php82/bin/php composer.phar install
            /opt/php82/bin/php artisan migrate --no-interaction
            /opt/php82/bin/php artisan view:clear --no-interaction
            /opt/php82/bin/php artisan db:seed --class=PermissionSeeder --no-interaction
            /opt/php82/bin/php artisan db:seed --class=SeoTemplateSeeder --no-interaction
