name: SSH deploy on push
on:
  push:
    branches: [ staging ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy & Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          password: ${{ secrets.STAGING_PASSWORD }}
          script: |
            cd public_html/
            git reset --hard
            git pull
            /usr/local/php/cgi/8.2/bin/php ../composer.phar install
            /usr/local/php/cgi/8.2/bin/php artisan migrate
            /usr/local/php/cgi/8.2/bin/php artisan view:clear
